# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{phpbb-auth}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Fawcett"]
  s.date = %q{2009-08-31}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{mail@matthewfawcett.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/phpbb_auth.rb",
     "lib/phpbb_auth/models/phpbb_session.rb",
     "lib/phpbb_auth/models/phpbb_user.rb",
     "lib/phpbb_auth/phpbb_auth.rb",
     "phpbb-auth.gemspec",
     "spec/config/phpbb_auth_settings.rb",
     "spec/db/forum.db",
     "spec/db/test.db",
     "spec/fixtures/forum_schema.rb",
     "spec/fixtures/test_schema.rb",
     "spec/models/phpbb_session_spec.rb",
     "spec/models/phpbb_user_spec.rb",
     "spec/phpbb_auth_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/mattfawcett/phpbb-auth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/config/phpbb_auth_settings.rb",
     "spec/models/phpbb_user_spec.rb",
     "spec/models/phpbb_session_spec.rb",
     "spec/phpbb_auth_spec.rb",
     "spec/fixtures/test_schema.rb",
     "spec/fixtures/forum_schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
