PHPBB_AUTH_FORUM_DATABASE_TABLE_PREFIX = 'phpbb_'
PHPBB_AUTH_COOKIE_NAME = "phpbb3_7uah4"
PHPBB_AUTH_LOCAL_USER_MODEL_NAME = "User"
PHPBB_AUTH_REMOTE_REMOTE_IDENTIFIER = 'user_email'
PHPBB_AUTH_REMOTE_LOCAL_IDENTIFIER = 'email'
PHPBB_AUTH_COLUMNS_TO_DUPLICATE = {:user_website => :website}
